name: Label Issues Based on Commit Messages

on:
  push:
    branches:
      - main

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Commit Messages
        run: |
          echo "Commit messages:"
          git log -1 --pretty=format:"%h %s"
